### PR TITLE
Fix FastGPT disappearing on settings toggle

### LINKED ISSUE #45: Right click summarize should open popup window
Right now it redirects to the summarize page, and only from the addon click will the popup appear.

### LINKED ISSUE #64: FastGPT vanishes when clicking on settings icon
https://github.com/kagisearch/browser_extensions/assets/32615971/f0a08449-bcc0-4a0c-89c1-5926b6a34c28

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Also change the context summarization to open in the popup as the extension, instead of a new tab.

This will be released on 0.5.1.

Fixes #45
Fixes #64

---

[kagi_chrome_0.5.1.zip](https://github.com/kagisearch/browser_extensions/files/14061551/kagi_chrome_0.5.1.zip)
[kagi_firefox_0.5.1.zip](https://github.com/kagisearch/browser_extensions/files/14061552/kagi_firefox_0.5.1.zip)

### CODE REVIEW

File: shared/src/background.js [hunk 1]
```diff
@@ -210,17 +210,22 @@ async function loadStorageData() {
...
-    )}`,
+
+  await browser.windows.create({
+    url: browser.runtime.getURL(
+      `src/summarize_result.html?url=${encodeURIComponent(url)}`,
+    ),
+    focused: true,
+    width: 600,
+    height: 500,
+    type: 'popup',
```
Comment (BrunoBernardino) [inline shared/src/background.js:224]: These changes fix opening up in the popup instead of a new tab with the summarizer (#45).

File: shared/src/popup.js [hunk 2]
```diff
@@ -273,9 +273,11 @@ async function setup() {
         if (!hasPermissions) {
           summarizeSection.style.display = 'none';
           requestPermissionsSection.style.display = '';
+          fastGptSection.style.display = 'none';
         } else {
           summarizeSection.style.display = '';
           requestPermissionsSection.style.display = 'none';
+          fastGptSection.style.display = '';
```
Comment (BrunoBernardino) [inline shared/src/popup.js:280]: These changes fix FastGPT disappearing when toggling settings (#65).

File: shared/src/summarize_result.js [hunk 3]
```diff
@@ -89,11 +89,16 @@ async function setup() {
 
     const searchParams = new URLSearchParams(window.location.search);
 
-    // If there's no URL, get the currently active tab and default params
-    if (!searchParams.get('url')) {
+    if (!searchParams.get('summary_type')) {
```
Comment (BrunoBernardino) [inline shared/src/summarize_result.js:92]: The changes in this file allow the popup to be initialized with _just_ a URL param (right click context open), otherwise not all parameters would've been properly set.
